apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::225989353406:role/EksCodeBuildKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::225989353406:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-SE2sck0cfyMF
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-24T17:16:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1502"
  uid: c185dcbc-57a1-4f5a-9df7-018b58a9f3e6
